name: Deb to IPA Converter
on: [push]
jobs:
 convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y binutils python3 python3-pip
      - name: Convert deb to ipa
        run: |
          mkdir -p payload/Applications
          ar x wechat-plugin.deb payload/Applications
          find.-name
          mkdir -p Payload/WeChat.app/Library/MobileSubstrate/DynamicLibraries && cp -r Library/MobileSubstrate/DynamicLibraries/* $_
          find payload/Applications -name "_CodeSignature" -type d | xargs rm -rf
          zip -r output.ipa Payload
